#######################################################
# 
# AsymmetricShape.py
# Python implementation of the Class AsymmetricShape
# Generated by Enterprise Architect
# Created on:      19-02-2017 23:21:50
# Original author: Drapegnik
# 
#######################################################
import Shape

class AsymmetricShape(Shape):
    def __init__(location, border_color, bg_color, point):
        pass

    def get_points():
        pass

    def render():
        pass

    def set_point(index, point):
        pass