#######################################################
# 
# Ellipse.py
# Python implementation of the Class Ellipse
# Generated by Enterprise Architect
# Created on:      19-02-2017 23:25:28
# Original author: Drapegnik
# 
#######################################################
import SymmetricShape

class Ellipse(SymmetricShape):
    def render():
        pass