#######################################################
# 
# Figure.py
# Python implementation of the Class Figure
# Generated by Enterprise Architect
# Created on:      19-02-2017 23:20:53
# Original author: Drapegnik
# 
#######################################################


class Figure:
    def __init__(location, border_color):
        pass

    def get_border_color():
        pass

    def get_location():
        pass

    def render():
        pass

    def set_border_color(color):
        pass

    def set_location(point):
        pass