#######################################################
# 
# Figure.py
# Python implementation of the Class Figure
# Generated by Enterprise Architect
# Created on:      19-02-2017 23:20:53
# Original author: Drapegnik
# 
#######################################################


class Figure:
    def __init__(self, location, border_color):
        pass

    def get_border_color(self):
        pass

    def get_location(self):
        pass

    def render(self):
        pass

    def set_border_color(self, color):
        pass

    def set_location(self, point):
        pass
