#######################################################
# 
# LineSegment.py
# Python implementation of the Class LineSegment
# Generated by Enterprise Architect
# Created on:      19-02-2017 23:25:27
# Original author: Drapegnik
# 
#######################################################
import Line

class LineSegment(Line):
    def render():
        pass