#######################################################
# 
# Line.py
# Python implementation of the Class Line
# Generated by Enterprise Architect
# Created on:      19-02-2017 23:25:27
# Original author: Drapegnik
# 
#######################################################
import Figure


class Line(Figure):
    def __init__(self, location, border_color, start_point, end_point):
        pass

    def get_end_point(self):
        pass

    def get_start_point(self):
        pass

    def render(self):
        pass

    def set_end_point(self, point):
        pass

    def set_start_point(self, point):
        pass
