#######################################################
# 
# Ray.py
# Python implementation of the Class Ray
# Generated by Enterprise Architect
# Created on:      19-02-2017 23:25:27
# Original author: Drapegnik
# 
#######################################################
import Line


class Ray(Line):
    def __init__(self, location, border_color, start_point, end_point, direction):
        pass

    def get_direction(self):
        pass

    def render(self):
        pass

    def set_direction(self, direction):
        pass
