#######################################################
# 
# RegularShape.py
# Python implementation of the Class RegularShape
# Generated by Enterprise Architect
# Created on:      19-02-2017 23:19:54
# Original author: Drapegnik
# 
#######################################################
import Shape

class RegularShape(Shape):
    def get_count():
        pass

    def get_second_point():
        pass

    def render():
        pass

    def set_count(count):
        pass

    def set_second_point(point):
        pass

    def __init__(location, border_color, bg_color, count, second_point):
        pass