#######################################################
# 
# Shape.py
# Python implementation of the Class Shape
# Generated by Enterprise Architect
# Created on:      19-02-2017 23:25:27
# Original author: Drapegnik
# 
#######################################################
import Figure


class Shape(Figure):
    def __init__(self, location, border_color, bg_color):
        pass

    def get_bg_color(self):
        pass

    def render(self):
        pass

    def set_bg_color(self, color):
        pass
