#######################################################
# 
# SymmetricShape.py
# Python implementation of the Class SymmetricShape
# Generated by Enterprise Architect
# Created on:      19-02-2017 23:25:28
# Original author: Drapegnik
# 
#######################################################
import RegularShape


class SymmetricShape(RegularShape):
    def __init__(self, location, border_color, bg_color, count, second_point, third_point):
        pass

    def render(self):
        pass

    def set_third_point(self, point):
        pass

    def set_third_point(self):
        pass
