dat<-read.table(file="input.txt", sep=",")
y<-t(dat)
a<-table(y)
f<-as.data.frame(a)
f[,3]<- 100*a/(sum(a))
f[,4]<- cumsum(a)
f[,5]<- cumsum(f[,3])
colnames(f)<-c("value","frequency","frequence","accum freq-cy","accum freq-ce")
plot(a,type="l",main="Poligon freq",xlab="value",ylab="frequency")
d<-as.numeric(y)
v<-sort(d)
x<-unique(v)
y<-as.numeric(f[,4])
plot(x,as.numeric(f[,4]),type="l",main="Accum absolut freq",xlab="value",ylab="accum freq")